// Mock data for the UK Care Provider Intelligence Dashboard.
// Complies with no em dash, no double/triple hyphen rules.

export const SAMPLE_ACCOUNTS = [
  {
    id: "sample-rushall",
    providerName: "Rushall Care Home",
    locationName: "Rushall Care Home Walsall",
    serviceType: "Care home",
    location: "Walsall",
    postcode: "WS4 1TG",
    address: "10 Rushall Lane, Walsall, West Midlands",
    phoneNumber: "01922 123456",
    website: "https://rushallcare.co.uk",
    emailAddress: "info@rushallcare.co.uk",
    cqcProviderId: "1-102938475",
    cqcLocationId: "1-564738291",
    cqcRating: "Requires Improvement",
    cqcInspectionDate: "2025-06-18",
    registeredManagerName: "Keith Jones",
    nominatedIndividualName: "Clara Oswald",
    regulatedActivities: ["Accommodation for persons who require nursing or personal care"],
    specialisms: ["Dementia support", "Old age care"],
    registrationStatus: "Active",
    companiesHouseName: "RUSHALL CARE HOME LIMITED",
    companiesHouseNumber: "08273645",
    isSample: true,
    checkedCqc: true,
    checkedCompaniesHouse: true,
    directors: ["Keith Jones", "Sarah Jones"],
    personsWithSignificantControl: ["Keith Jones"],
    incorporationDate: "2020-04-12"
  },
  {
    id: "sample-1",
    providerName: "Greenvale Residential Care",
    locationName: "Greenvale Residential Care Bristol Branch",
    serviceType: "Care home",
    location: "Bristol",
    postcode: "BS1 5AA",
    address: "12 Greenvale Lane, Clifton, Bristol",
    phoneNumber: "0117 123 4567",
    website: "https://greenvalecare.co.uk",
    emailAddress: "manager@greenvalecare.co.uk",
    cqcProviderId: "1-123456789",
    cqcLocationId: "1-987654321",
    cqcRating: "Requires Improvement",
    cqcInspectionDate: "2025-11-12",
    registeredManagerName: "Sarah Jenkins",
    nominatedIndividualName: "David Cole",
    regulatedActivities: ["Accommodation for persons who require nursing or personal care"],
    specialisms: ["Dementia", "Physical disabilities", "Caring for adults over 65 yrs"],
    registrationStatus: "Active",
    companiesHouseName: "GREENVALE CARE LIMITED",
    companiesHouseNumber: "01234567",
    isSample: true,
    checkedCqc: true,
    checkedCompaniesHouse: true,
    directors: ["David Cole", "Sarah Jenkins"],
    personsWithSignificantControl: ["David Cole"],
    incorporationDate: "2015-06-15"
  },
  {
    id: "sample-2",
    providerName: "Oakbridge Homecare",
    locationName: "Oakbridge Homecare Birmingham",
    serviceType: "Homecare",
    location: "Birmingham",
    postcode: "B2 4QA",
    address: "Suite 4B, Colmore Business District, Birmingham",
    phoneNumber: "0121 987 6543",
    website: "https://oakbridgehomecare.co.uk",
    emailAddress: "admin@oakbridgehomecare.co.uk",
    cqcProviderId: "1-234567890",
    cqcLocationId: "1-876543210",
    cqcRating: "Good",
    cqcInspectionDate: "2025-08-20",
    registeredManagerName: "Michael Chang",
    nominatedIndividualName: "Emma Watson",
    regulatedActivities: ["Personal care"],
    specialisms: ["Caring for adults over 65 yrs", "Dementia", "Sensory impairments"],
    registrationStatus: "Active",
    companiesHouseName: "OAKBRIDGE HEALTHCARE LTD",
    companiesHouseNumber: "07654321",
    isSample: true,
    checkedCqc: true,
    checkedCompaniesHouse: true,
    directors: ["Emma Watson"],
    personsWithSignificantControl: ["Emma Watson"],
    incorporationDate: "2018-09-01"
  },
  {
    id: "sample-3",
    providerName: "Meadow Support Living",
    locationName: "Meadow Support Living Co",
    serviceType: "Supported living",
    location: "Manchester",
    postcode: "M1 1AD",
    address: "1 Meadow Way, Salford, Manchester",
    phoneNumber: "Not found in verified source",
    website: "Not found in verified source",
    emailAddress: "Not found in verified source",
    cqcProviderId: "Not found in verified source",
    cqcLocationId: "Not found in verified source",
    cqcRating: "Not found in verified source",
    cqcInspectionDate: "Not found in verified source",
    registeredManagerName: "Not found in verified source",
    nominatedIndividualName: "Not found in verified source",
    regulatedActivities: [],
    specialisms: [],
    registrationStatus: "Not found in verified source",
    companiesHouseName: "MEADOW SUPPORT LIVING CO.",
    companiesHouseNumber: "08901234",
    isSample: true,
    checkedCqc: false,
    checkedCompaniesHouse: true,
    directors: ["Jane Meadow"],
    personsWithSignificantControl: ["Jane Meadow"],
    incorporationDate: "2022-03-10"
  }
];

export const MOCK_CQC_RECORDS = {
  "Rushall Care Home": {
    providerName: "Rushall Care Home",
    locationName: "Rushall Care Home Walsall",
    cqcProviderId: "1-102938475",
    cqcLocationId: "1-564738291",
    serviceType: "Care home",
    address: "10 Rushall Lane, Walsall, West Midlands",
    postcode: "WS4 1TG",
    phoneNumber: "01922 123456",
    website: "https://rushallcare.co.uk",
    emailAddress: "info@rushallcare.co.uk",
    registeredManagerName: "Keith Jones",
    nominatedIndividualName: "Clara Oswald",
    latestCqcRating: "Requires Improvement",
    latestInspectionDate: "2025-06-18",
    regulatedActivities: ["Accommodation for persons who require nursing or personal care"],
    specialisms: ["Dementia support", "Old age care"],
    serviceUserBands: ["Adults", "Older people"],
    providerRegistrationStatus: "Active",
    locationRegistrationStatus: "Active"
  },
  "Greenvale Residential Care": {
    providerName: "Greenvale Residential Care",
    locationName: "Greenvale Residential Care Bristol Branch",
    cqcProviderId: "1-123456789",
    cqcLocationId: "1-987654321",
    serviceType: "Care home",
    address: "12 Greenvale Lane, Clifton, Bristol",
    postcode: "BS1 5AA",
    phoneNumber: "0117 123 4567",
    website: "https://greenvalecare.co.uk",
    emailAddress: "manager@greenvalecare.co.uk",
    registeredManagerName: "Sarah Jenkins",
    nominatedIndividualName: "David Cole",
    latestCqcRating: "Requires Improvement",
    latestInspectionDate: "2025-11-12",
    regulatedActivities: ["Accommodation for persons who require nursing or personal care"],
    specialisms: ["Dementia", "Physical disabilities", "Caring for adults over 65 yrs"],
    serviceUserBands: ["Adults", "Older people"],
    providerRegistrationStatus: "Active",
    locationRegistrationStatus: "Active"
  },
  "Oakbridge Homecare": {
    providerName: "Oakbridge Homecare Agency",
    locationName: "Oakbridge Homecare Birmingham",
    cqcProviderId: "1-234567890",
    cqcLocationId: "1-876543210",
    serviceType: "Homecare",
    address: "Suite 4B, Colmore Business District, Birmingham",
    postcode: "B2 4QA",
    phoneNumber: "0121 987 6543",
    website: "https://oakbridgehomecare.co.uk",
    emailAddress: "admin@oakbridgehomecare.co.uk",
    registeredManagerName: "Michael Chang",
    nominatedIndividualName: "Emma Watson",
    latestCqcRating: "Good",
    latestInspectionDate: "2025-08-20",
    regulatedActivities: ["Personal care"],
    specialisms: ["Caring for adults over 65 yrs", "Dementia", "Sensory impairments"],
    serviceUserBands: ["Adults", "Older people"],
    providerRegistrationStatus: "Active",
    locationRegistrationStatus: "Active"
  }
};

export const MOCK_COMPANIES_HOUSE_RECORDS = {
  "08273645": {
    registeredCompanyName: "RUSHALL CARE HOME LIMITED",
    companyNumber: "08273645",
    companyStatus: "active",
    incorporationDate: "2020-04-12",
    registeredOfficeAddress: "10 Rushall Lane, Walsall, WS4 1TG",
    sicCodes: ["87100 - Residential nursing care activities"],
    directors: ["Keith Jones", "Sarah Jones"],
    personsWithSignificantControl: ["Keith Jones"],
    filingHistorySummary: "Accounts filed up to 31 December 2024. Next confirmation statement due April 2027.",
    accountsStatus: "up to date",
    confirmationStatementStatus: "up to date"
  },
  "01234567": {
    registeredCompanyName: "GREENVALE CARE LIMITED",
    companyNumber: "01234567",
    companyStatus: "active",
    incorporationDate: "2015-06-15",
    registeredOfficeAddress: "12 Greenvale Lane, Clifton, Bristol, BS1 5AA",
    sicCodes: ["87100 - Residential nursing care activities"],
    directors: ["David Cole", "Sarah Jenkins"],
    personsWithSignificantControl: ["David Cole"],
    filingHistorySummary: "Accounts filed up to 31 December 2024. Next confirmation statement due July 2026.",
    accountsStatus: "up to date",
    confirmationStatementStatus: "up to date"
  },
  "07654321": {
    registeredCompanyName: "OAKBRIDGE HEALTHCARE LTD",
    companyNumber: "07654321",
    companyStatus: "active",
    incorporationDate: "2018-09-01",
    registeredOfficeAddress: "Suite 4B, Colmore Business District, Birmingham, B2 4QA",
    sicCodes: ["88100 - Social work activities without accommodation for the elderly and disabled"],
    directors: ["Emma Watson"],
    personsWithSignificantControl: ["Emma Watson"],
    filingHistorySummary: "Accounts filed up to 31 March 2025. Confirmation statement due September 2026.",
    accountsStatus: "up to date",
    confirmationStatementStatus: "up to date"
  },
  "08901234": {
    registeredCompanyName: "MEADOW SUPPORT LIVING CO.",
    companyNumber: "08901234",
    companyStatus: "active",
    incorporationDate: "2022-03-10",
    registeredOfficeAddress: "1 Meadow Way, Salford, Manchester, M1 1AD",
    sicCodes: ["87200 - Residential care activities for learning difficulties, mental health and substance abuse"],
    directors: ["Jane Meadow"],
    personsWithSignificantControl: ["Jane Meadow"],
    filingHistorySummary: "Accounts filed up to 31 December 2024. Confirmation statement overdue by 14 days.",
    accountsStatus: "up to date",
    confirmationStatementStatus: "overdue"
  }
};
