// Mock data for the UK Care Provider Intelligence Dashboard.
// All contents comply with the rule of no double hyphens, triple hyphens, or em dashes.

export const SAMPLE_ACCOUNTS = [
  {
    id: "sample-1",
    providerName: "Greenvale Residential Care",
    serviceType: "Care home",
    location: "Bristol",
    postcode: "BS1 5AA",
    residentsCount: 34,
    staffCount: 42,
    bedsCount: 36,
    currentCarePlanning: "Paper records",
    currentRostering: "Spreadsheets",
    currentEMar: "Paper records",
    currentPayroll: "Spreadsheets",
    cqcRating: "Requires Improvement",
    cqcInspectionDate: "2025-11-12",
    painPoints: "Audit preparation and manual care notes",
    timeline: "Reviewing systems this quarter",
    registeredManagerName: "Sarah Jenkins",
    nominatedIndividualName: "David Cole",
    companiesHouseName: "GREENVALE CARE LIMITED",
    companiesHouseNumber: "01234567",
    isSample: true,
    checkedCqc: true,
    checkedCompaniesHouse: true,
    cqcRatingDetails: "The inspection found issues in safe care and treatment, particularly medication administration records and manual care planning documentation, leading to a Requires Improvement rating.",
    companiesHouseDetails: "Status: Active. Accounts filed up to date. Directorship list matches David Cole."
  },
  {
    id: "sample-2",
    providerName: "Oakbridge Homecare",
    serviceType: "Homecare",
    location: "Birmingham",
    postcode: "B2 4QA",
    clientsCount: 58,
    staffCount: 41,
    currentCarePlanning: "Paper records",
    currentRostering: "CarePlanner",
    currentEMar: "Paper records",
    currentPayroll: "Sage",
    cqcRating: "Good",
    cqcInspectionDate: "2025-08-20",
    painPoints: "Care note visibility and office admin",
    timeline: "Contract renewal in 4 months",
    registeredManagerName: "Michael Chang",
    nominatedIndividualName: "Emma Watson",
    companiesHouseName: "OAKBRIDGE HEALTHCARE LTD",
    companiesHouseNumber: "07654321",
    isSample: true,
    checkedCqc: true,
    checkedCompaniesHouse: true,
    cqcRatingDetails: "Effective care plans and robust daily recording are in place, but records are stored as physical paper sheets leading to visual information latency.",
    companiesHouseDetails: "Status: Active. Confirmation statement next due in 2 months. Directors: Emma Watson."
  },
  {
    id: "sample-3",
    providerName: "Meadow Support Living",
    serviceType: "Supported living",
    location: "Manchester",
    postcode: "M1 1AD",
    clientsCount: 19,
    staffCount: 28,
    currentCarePlanning: "LogMyCare",
    currentRostering: "LogMyCare",
    currentEMar: "LogMyCare",
    currentPayroll: "Xero",
    cqcRating: "Not found",
    cqcInspectionDate: "",
    painPoints: "Oversight across multiple houses",
    timeline: "Needs manual verification",
    registeredManagerName: "Not found in API data",
    nominatedIndividualName: "Not found in API data",
    companiesHouseName: "MEADOW SUPPORT LIVING CO.",
    companiesHouseNumber: "08901234",
    isSample: true,
    checkedCqc: false,
    checkedCompaniesHouse: true,
    cqcRatingDetails: "No regulatory record could be found under this exact name. Manual registration checks are recommended.",
    companiesHouseDetails: "Status: Active. Incorporate date: 2022-03-10."
  }
];

export const MOCK_CQC_RECORDS = {
  "Greenvale Residential Care": {
    providerName: "Greenvale Residential Care",
    locationName: "Greenvale Residential Care Bristol Branch",
    cqcProviderId: "1-123456789",
    cqcLocationId: "1-987654321",
    serviceType: "Care home",
    address: "12 Greenvale Lane, Clifton, Bristol",
    postcode: "BS1 5AA",
    registeredManagerName: "Sarah Jenkins",
    nominatedIndividualName: "David Cole",
    latestCqcRating: "Requires Improvement",
    latestInspectionDate: "2025-11-12",
    regulatedActivities: ["Accommodation for persons who require nursing or personal care"],
    specialisms: ["Dementia", "Physical disabilities", "Caring for adults over 65 yrs"],
    serviceUserBands: ["Adults", "Older people"],
    providerRegistrationStatus: "Active",
    locationRegistrationStatus: "Active"
  },
  "Oakbridge Homecare": {
    providerName: "Oakbridge Homecare Agency",
    locationName: "Oakbridge Homecare Birmingham",
    cqcProviderId: "1-234567890",
    cqcLocationId: "1-876543210",
    serviceType: "Homecare",
    address: "Suite 4B, Colmore Business District, Birmingham",
    postcode: "B2 4QA",
    registeredManagerName: "Michael Chang",
    nominatedIndividualName: "Emma Watson",
    latestCqcRating: "Good",
    latestInspectionDate: "2025-08-20",
    regulatedActivities: ["Personal care"],
    specialisms: ["Caring for adults over 65 yrs", "Dementia", "Sensory impairments"],
    serviceUserBands: ["Adults", "Older people"],
    providerRegistrationStatus: "Active",
    locationRegistrationStatus: "Active"
  }
};

export const MOCK_COMPANIES_HOUSE_RECORDS = {
  "01234567": {
    registeredCompanyName: "GREENVALE CARE LIMITED",
    companyNumber: "01234567",
    companyStatus: "active",
    incorporationDate: "2015-06-15",
    registeredOfficeAddress: "12 Greenvale Lane, Clifton, Bristol, BS1 5AA",
    sicCodes: ["87100 - Residential nursing care activities"],
    directors: ["David Cole", "Sarah Jenkins"],
    personsWithSignificantControl: ["David Cole"],
    filingHistorySummary: "Accounts filed up to 31 December 2024. Next confirmation statement due July 2026.",
    accountsStatus: "up to date",
    confirmationStatementStatus: "up to date"
  },
  "07654321": {
    registeredCompanyName: "OAKBRIDGE HEALTHCARE LTD",
    companyNumber: "07654321",
    companyStatus: "active",
    incorporationDate: "2018-09-01",
    registeredOfficeAddress: "Suite 4B, Colmore Business District, Birmingham, B2 4QA",
    sicCodes: ["88100 - Social work activities without accommodation for the elderly and disabled"],
    directors: ["Emma Watson"],
    personsWithSignificantControl: ["Emma Watson"],
    filingHistorySummary: "Accounts filed up to 31 March 2025. Confirmation statement due September 2026.",
    accountsStatus: "up to date",
    confirmationStatementStatus: "up to date"
  },
  "08901234": {
    registeredCompanyName: "MEADOW SUPPORT LIVING CO.",
    companyNumber: "08901234",
    companyStatus: "active",
    incorporationDate: "2022-03-10",
    registeredOfficeAddress: "1 Meadow Way, Salford, Manchester, M1 1AD",
    sicCodes: ["87200 - Residential care activities for learning difficulties, mental health and substance abuse"],
    directors: ["Jane Meadow"],
    personsWithSignificantControl: ["Jane Meadow"],
    filingHistorySummary: "Accounts filed up to 31 December 2024. Confirmation statement overdue by 14 days.",
    accountsStatus: "up to date",
    confirmationStatementStatus: "overdue"
  }
};
